import { Webhook } from "discord.js"

export interface configType {
        activeBanshareFuncionUserIds: string[],
        activeWebhooks: Webhook[],
        aeonBanshareChannelId: string,
        approvalCountNeededForImportantBanshare: number,
        birbId: string,
        cachedEmojiUids: string[],
        cleanDbMode: boolean,
        conductorRoleId: string,
        crowdControlActive: boolean,
        crowdControlChannelId: string,
        currentLogFileName: string,
        debugMode: boolean,
        devIds: string[],
        disabledStickerNetworkServerIds: string[], //This will be put into the db soon, im just lazy
        embedFieldLimit: number,
        emojiServerIds: string[],
        enableStickers: boolean,
        infoMessageChannelId: string,
        infoMessageId: string,
        mainServerId: string,
        maxConcurrentRequestCount: number,
        maxEmbedColumnValueLength: number,
        maxEmojiPerServer: number,
        modmailCategoryChannelId: string,
        modmailLogChannelId: string,
        navigatorRoleId: string,
        networkJoinChannelId: string,
        nonChatWebhooks: string[],
        nonChatWebhooksTypes: string[],
        numberOfDaysLogsAreDeletedAfter: number,
        numberOfMessagesToLoad: number,
        privateNotificationChannelId: string,
        publicNotificationChannelId: string,
        replyArrowEmojiId: string,
        replyPictureEmojiId: string,
        tempBanshareServerId: string,
        suspendedPermissionUserIds: string[],
        representativeRoleId: string,
        botStarting: boolean
    }