import { Webhook } from "discord.js"

export interface configType {
    clientName: string,
    maxServerPerClient: number,
    loadedClients: number,
    tokens: string[],
    activeBanshareFuncionUserIds: string[],
    activeWebhooks: Webhook[],
    aeonBanshareChannelId: string,
    approvalCountNeededForImportantBanshare: number,
    birbId: string,
    cachedEmojiUids: string[],
    cleanDbMode: boolean,
    conductorRoleId: string,
    crowdControlActive: boolean,
    crowdControlChannelId: string,
    currentLogFileName: string,
    debugMode: boolean,
    devIds: string[],
    /* disabledStickerNetworkServerIds is depricated
        use DatabaseManager.getAllServerStickerStatus();
    */
    disabledStickerNetworkServerIds: string[],
    embedFieldLimit: number,
    enableStickers: boolean,
    emojiServerIds: string[],
    infoMessageChannelId: string,
    infoMessageId: string,
    mainServerId: string,
    maxConcurrentRequestCount: number,
    maxEmbedColumnValueLength: number,
    maxEmojiPerServer: number,
    modmailCategoryChannelId: string,
    modmailLogChannelId: string,
    navigatorRoleId: string,
    networkJoinChannelId: string,
    nonChatWebhooks: string[],
    nonChatWebhooksTypes: string[],
    numberOfDaysLogsAreDeletedAfter: number,
    numberOfMessagesToLoad: number,
    privateNotificationChannelId: string,
    publicNotificationChannelId: string,
    replyArrowEmojiId: string,
    replyPictureEmojiId: string,
    tempBanshareServerId: string,
    suspendedPermissionUserIds: string[],
    representativeRoleId: string,
    botStarting: boolean,
    databaseUsername: string,
    databasePassword: string,
    databaseHost: string,
    databasePort: number,
    databaseName: string,
}