import { Webhook } from "discord.js"
import { getEnvVar } from "./get-env-var"
import { UidUserPair } from "./types/blacklist-words"

export const config = {
    activeBanshareFuncionUserIds: [] as string[],
    activeWebhooks: [] as Webhook[],
    aeonBanshareChannelId: getEnvVar<string>("AEON_BANSHARE_CHANNEL_ID"),
    approvalCountNeededForImportantBanshare: 2,
    birbId: getEnvVar<string>("BIRB_ID"),
    cachedEmojiUids: [] as string[],
    cleanDbMode: true,
    conductorRoleId: getEnvVar<string>("CONDUCTOR_ROLE_ID"),
    crowdControlActive: false,
    crowdControlChannelId: getEnvVar<string>("CROWD_CONTROL_CHANNEL_ID"),
    currentLogFileName: '',
    debugMode: false,
    devIds: getEnvVar<string>("DEV_IDS").split(' '),
    disabledStickerNetworkServerIds: ["1068066545344970783"] as string[], //This will be put into the db soon, im just lazy
    embedFieldLimit: 25,
    emojiServerIds: getEnvVar<string>("EMOJI_SERVER_IDS").split(' '),
    enableStickers: true,
    infoMessageChannelId: getEnvVar<string>("INFO_MESSAGE_CHANNEL_ID"),
    infoMessageId: getEnvVar<string>("INFO_MESSAGE_ID"),
    mainServerId: getEnvVar<string>("MAIN_SERVER_ID"),
    maxConcurrentRequestCount: 10,
    maxEmbedColumnValueLength: 1024,
    maxEmojiPerServer: 50,
    modmailCategoryChannelId: getEnvVar<string>("MODMAIL_CATEGORY_CHANNEL_ID"),
    modmailLogChannelId: getEnvVar<string>("MODMAIL_LOG_CHANNEL_ID"),
    navigatorRoleId: getEnvVar<string>("NAVIGATOR_ROLE_ID"),
    networkJoinChannelId: getEnvVar<string>("NETWORK_JOIN_CHANNEL_ID"),
    nonChatWebhooks: getEnvVar<string>("NON_CHAT_WEBHOOKS").split(','),
    nonChatWebhooksTypes: getEnvVar<string>("NON_CHAT_WEBHOOK_TYPES").split(' '),
    numberOfDaysLogsAreDeletedAfter: 7,
    numberOfMessagesToLoad: 100,
    privateNotificationChannelId: getEnvVar<string>("PRIVATE_NOTIFICATION_CHANNEL_ID"),
    publicNotificationChannelId: getEnvVar<string>("PUBLIC_NOTIFICATION_CHANNEL_ID"),
    replyArrowEmojiId: getEnvVar<string>("REPLY_ARROW_EMOJI_ID"),
    replyPictureEmojiId: getEnvVar<string>("REPLY_PICTURE_EMOJI_ID"),
    tempBanshareServerId: getEnvVar<string>("TEMP_BANSHARE_SERVER_ID"),
    websiteUids: [] as UidUserPair[],
    suspendedPermissionUserIds: [] as string[],
    representativeRoleId: getEnvVar<string>("REPRESENTATIVE_ROLE_ID"),
    botStarting: false
}
